version: '0.1'

services:
  python:
    image: python:latest
    volumes:
      - './projects:/var/www/html'
    container_name: python
    tty: true
    working_dir: '/var/www/html'

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
